# Generated by Django 3.0.5 on 2020-04-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appanswer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='imageoffirstpage',
            name='ofFirstPage',
        ),
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.RemoveField(
            model_name='secondpage',
            name='ofFirstPage',
        ),
        migrations.DeleteModel(
            name='FirstPage',
        ),
        migrations.DeleteModel(
            name='ImageOfFirstPage',
        ),
        migrations.DeleteModel(
            name='SecondPage',
        ),
    ]
